import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#FBF9F7" },
  content: { padding: 16, paddingBottom: 48 },
  backRow: { flexDirection: "row", alignItems: "center", marginBottom: 8 },
  backArrow: { fontSize: 28, color: "#6b6b6b", marginRight: 8 },
  backText: { color: "#6b6b6b" },

  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
    marginBottom: 12,
  },
  iconWrap: {
    width: 56,
    height: 56,
    borderRadius: 12,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  icon: { width: 44, height: 44, borderRadius: 8 },
  headerTextWrap: { flex: 1 },
  headerTitle: { marginBottom: 6, color: "#263238" },
  headerSubtitle: { color: "#7a7a7a" },
  infoText: { color: "#6a4946", lineHeight: 20 },
  sectionTitle: { marginTop: 6, marginBottom: 8, color: "#263238" },

  infoBox: {
    backgroundColor: "#FFF3F2",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "#F5D3D1",
    marginBottom: 12,
  },
  photoPlaceholder: {
    height: 86,
    width: 86,
    borderRadius: 10,
    borderStyle: "dashed",
    borderWidth: 1.5,
    borderColor: "#e2dcd9",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  photoIcon: { fontSize: 20, color: "#9a9a9a" },
  photoLabel: { color: "#9a9a9a", marginTop: 6 },
  photoHint: { color: "#9a9a9a", marginTop: 8, marginBottom: 12 },
  photoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  photoThumb: {
    width: 86,
    height: 86,
    borderRadius: 10,
    backgroundColor: "#fff",
  },

  fieldLabel: { marginTop: 8, marginBottom: 6, color: "#333" },
  input: {
    backgroundColor: "#fff",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#efe9e5",
    marginBottom: 8,
  },
  selectInput: {
    backgroundColor: "#fff",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "#efe9e5",
    marginBottom: 8,
  },
  selectText: { color: "#7a7a7a" },
  pickerWrap: {
    borderRadius: 10,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#efe9e5",
    backgroundColor: "#fff",
    marginBottom: 8,
  },
  pickerButton: { justifyContent: "center" },
  rowInputs: { flexDirection: "row", gap: 8 },
  smallInput: { flex: 1 },

  mapPlaceholder: {
    height: 160,
    backgroundColor: "#fff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#efe9e5",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  mapHint: { color: "#9a9a9a", marginBottom: 8 },
  mapSearchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  searchInput: {
    flex: 1,
    backgroundColor: "#fff",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#efe9e5",
  },
  searchButton: {
    marginLeft: 8,
    backgroundColor: "#fff",
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#efe9e5",
    alignItems: "center",
    justifyContent: "center",
  },
  suggestionsList: {
    backgroundColor: "#fff",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#efe9e5",
    marginBottom: 8,
    maxHeight: 160,
  },
  suggestionItem: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#f0eeec",
  },
  suggestionText: { color: "#333" },
  mapContainer: {
    height: 200,
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 8,
  },
  map: { flex: 1 },
  coordsText: { color: "#9a9a9a", marginBottom: 12 },

  multiline: { minHeight: 86, textAlignVertical: "top" },

  promoBox: {
    backgroundColor: "#FFF7F3",
    borderRadius: 12,
    padding: 12,
    marginVertical: 12,
    borderWidth: 1,
    borderColor: "#F2D9D6",
  },
  promoRow: { flexDirection: "row", alignItems: "center", marginBottom: 8 },
  promoRadio: { marginRight: 10, color: "#DD6A5A" },
  promoText: { color: "#6a4946" },
  promoSelected: {
    backgroundColor: "#FFF0EE",
    borderWidth: 1,
    borderColor: "#F2D9D6",
  },

  submitButton: {
    backgroundColor: "#DF2D2D",
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 12,
    marginBottom: 40,
  },
  submitButtonText: { color: "#fff" },
});
