import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  headerBlock: { paddingTop: 10, paddingHorizontal: 2 },
  title: { fontSize: 20, marginBottom: 6 },
  subtitle: { color: "#666", marginBottom: 6 },
  primaryButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
    alignSelf: "flex-start",
  },
  primaryButtonText: { color: "#fff", marginLeft: 8, fontWeight: "600" },
  controlsRow: { flexDirection: "row", alignItems: "center", gap: 4 },
  searchWrap: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#eee",
  },
  searchInput: { marginLeft: 4, flex: 1, height: 40 },
  selector: {
    marginLeft: 12,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#eee",
  },
  resultsCount: { marginTop: 12, color: "#666" },
  list: { padding: 16, paddingTop: 8 },
  card: {
    backgroundColor: "#fff",
    borderRadius: 12,
    marginBottom: 16,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  cardImage: { width: "100%", height: 180 },
  tagPill: {
    position: "absolute",
    top: 12,
    left: 12,
    backgroundColor: "#2f9e44",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
  },
  tagText: { color: "#fff", fontSize: 12, fontWeight: "600" },
  heartWrap: {
    position: "absolute",
    top: 12,
    right: 12,
    backgroundColor: "rgba(255,255,255,0.9)",
    padding: 8,
    borderRadius: 18,
  },
  cardBody: { padding: 12 },
  petName: { fontSize: 16, color: "#222" },
  genderBadge: {
    backgroundColor: "#f2f2f2",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    minWidth: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  genderText: { fontSize: 12, color: "#666", textAlign: "center" },
  breed: { color: "#777", marginTop: 6 },
  locationRow: { flexDirection: "row", alignItems: "center", marginTop: 8 },
  locationText: { color: "#999", marginLeft: 6 },
  cardPagerDots: {
    position: "absolute",
    bottom: 8,
    left: 12,
    right: 12,
    flexDirection: "row",
    justifyContent: "center",
    gap: 6,
  },
  cardDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "rgba(255,255,255,0.5)",
  },
  cardDotActive: {
    backgroundColor: "#fff",
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  filterBar: {
    marginTop: 12,
    borderWidth: 2,
    borderRadius: 10,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  filterPanel: {
    marginTop: 10,
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#eee",
  },
  filterRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 8,
  },
  filterSelect: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#eee",
  },
  attributesRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  attr: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#eee",
    marginRight: 8,
  },
  attrActive: {
    // will be adjusted inline using tint from component
    backgroundColor: "#ff8c42",
    borderColor: "#ff8c42",
    color: "#fff",
  },
});
